camptocamp/terraboard

db/db.go

When fields contain non-ASCII data (e.g. cloud-init's rendered field, when gzipped), the state fails to import to database. 
To avoid this, we are detecting non-ASCII characters and avoiding insertion of these attributes.

Do not import non-ASCII data

---

static/search.html
static/terraboard.css
static/terraboard.js

Fix design bugs and add the possibility to create permalinks.

Improve search engine

---

Dockerfile
Makefile
README.md
api/api.go
auth/auth.go
auth/auth_test.go
config/config.go
docker-compose.yml
main.go
static/navbar.html
static/terraboard.js

This is a WIP to display authentication info when an auth proxy is used.
The current state of the PoC:
* checks for an `X-Forwarded-Access-Token` header, gets info from GitHub when passed (only Github is supported so far)
* If no `X-Forwarded-Access-Token` header is passed, uses `X-Forwarded-User` and `X-Forwarded-Email`, using gravatar for the avatar URL.

Authentication info

---

main.go

If Terraboard experiences an error getting the state from s3, log this, and continue without crashing.
Without this, Terraboard may crash at [db.go:51](https://github.com/camptocamp/terraboard/blob/2f61655ca8868dffb9caac3a189aab531fd8efc4/db/db.go#L51) when trying to access `state.TFVersion`.

Report errors fetching state from S3

---

types/db.go

This was broken by 885a4215615bd747ee09cd46a7e136b10f476640

Fix json field for value

---

README.md
docker-compose.yml

Hey @raphink - I pinged you a couple days ago about using docker links vs networks. I'd actually not looked at the repo's compose file, just read the instructions in the readme and then adjusted them to fit.
Since the compose file is already v3, using networks instead of links pretty much means removing the 'link' syntax - docker-compose sets up a [default app network](https://docs.docker.com/compose/networking/) and sticks all containers in a single compose file on that network, so they get connectivity out the box. This PR does that, with the caveat I don't have an oauth provider handy to test the proxy piece on so didn't tested that forwards correctly without a link set up.
The `http://terraboard:8080/terraboard/` syntax remains the same without links in place though, so it probably …

Remove deprecated links, use compose default network

---

main_test.go

Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://travis-ci.org/camptocamp/terraboard/builds/463752139
./main_test.go:18: T.Fatalf format %s has arg true of wrong type bool
./main_test.go:29: T.Fatalf format %s has arg false of wrong type bool
FAIL	github.com/camptocamp/terraboard [build failed]

Correct Travis fail

---

go.mod

This is a rather stupid update but I think that some might find it useful: I've changed and tested ability to use Terraboard with .tfstate files created in Terraform of versions higher than 12.8 (up to 12.18) and I need to say that it works as expected. The only change that has to be made is the version of terraform in go.mod file. 
p.s: I've tested this setup by building a docker image and running it along with the postgres container.

Add support for newer terraform versions

---

db/db.go

I believe it makes more sense to set these logs at the debug level.

Reduce the noise in the logs when parsing statefiles

---

config/config.go

Since the golang pq package doesn't support "prefer"
See https://github.com/camptocamp/terraboard/issues/76#issuecomment-581653971

Make database sslmode default to require

---

README.md

This seems to be an oversight in the README, config/config.go references TERRABOARD_PORT

change PORT to TERRABOARD_PORT in README.md

---

README.md
go.mod
go.sum

No sure in terms of tagging, but I guess it is time to upgrade to 12.24  - tests did not show nothing broken, coverage also looked same.

update to use terraform 0.12.24

---

README.md
config/config.go
go.mod
go.sum
state/aws.go

Enables the use of external ARN to assume role for cross-account access.

Add AWS ARN Support

---

.revive.toml
.travis.yml
Makefile
api/api.go
main_test.go
state/gcp.go

- Manage go tools more efficiently within the make calls
- Manage the lint tests using mgechev/revive
- Added gosec tests -- TODO: fix the ~34 issues discovered
- Added ineffassign tests
- Added misspell tests
- Fixed some lint and misspell errors
- Updated travis config and added a make call to manage coveralls

Enhanced Makefile and testing implementation

---

Makefile
api/api.go
db/db.go
main.go

I fixed the 32 out of the 34 discovered gosec issues. Choosing to ignore the ones related to `crypto/md5` as those are necessary for gravatar support.
```
[/terraboard/auth/auth.go:32] - G401 (CWE-326): Use of weak cryptographic primitive (Confidence: HIGH, Severity: MEDIUM)
31: 		user.Name = name
> 32: 		user.AvatarURL = fmt.Sprintf("http://www.gravatar.com/avatar/%x", md5.Sum([]byte(email)))
33: 	}
[/terraboard/auth/auth.go:4] - G501 (CWE-327): Blocklisted import crypto/md5: weak cryptographic primitive (Confidence: HIGH, Severity: MEDIUM)
3: import (
> 4: 	"crypto/md5"
5: 	"fmt"
[/terraboard/main.go:86] - G601 (CWE-118): Implicit memory aliasing in for loop. (Confidence: MEDIUM, Severity: MEDIUM)
85: 				} else {
> 86: 					d.InsertVersion(&v)
87: 				}
[/terraboard/api/api.go:221] - …
```

Implemented gosec as part of the testing workflow

---

db/db.go
state/aws.go
static/search.html
static/state.html
types/db.go
types/search.go

Changes proposed to fix https://github.com/camptocamp/terraboard/issues/97.
It adds support for multiple resources created under the same type and name. This is the use case when `count` or `for_each` are used.
Additionally:
- Modify **state** representation to add resource index
- Modify **search** table to add resource type and resource index under "Resource ID" column

Add support for multiple instances of the same resource

---

Makefile

tests are now failing: https://travis-ci.org/github/camptocamp/terraboard/builds/754109002
```
ineffassign compare/compare_test.go compare/compare.go db/db.go db/db_test.go config/config.go config/config_test.go auth/auth.go auth/auth_test.go api/api.go api/api_test.go util/util.go util/util_test.go types/db.go types/search_test.go types/compare_test.go types/db_test.go types/search.go types/compare.go state/tfe_test.go state/aws_test.go state/state_test.go state/gcp_test.go state/tfe.go state/aws.go state/state.go state/gcp.go
-: named files must all be in one directory; have compare/ and db/
ineffassign: error during loading
Makefile:40: recipe for target 'ineffassign' failed
make: *** [ineffassign] Error 1
```

Fixed ineffassign definition following a recent update

---

README.md
config/config.go
config/config_test.go
config/config_test.yml
db/db.go
go.mod
go.sum
main.go
pkg/client/gitlab/gitlab.go
pkg/client/gitlab/gitlab_test.go
state/gcp.go
state/gitlab.go
state/gitlab_test.go
state/state.go
state/tfe.go

Hacked my way around the few possibilities that GitLab offers to fetch all the information that Terraboard needs to be able to leverage it as a backend provider 😁 
There seems to be active development around this so I would expect it gets easier to achieve over time. There is only one outstanding thing which may be worth to wait for : https://gitlab.com/gitlab-org/gitlab/-/merge_requests/45851
However it did not seem to impact the data being stored somehow 🤔 🤷

Added support for GitLab as terraform state backend provider

---

README.md
docker-compose.yml
hugo/config.toml

For https://github.com/camptocamp/terraboard/issues/118

option to switch go dns resolver

---

db/db.go

Terraform `ResourceInstance.Current` can be [`nil`](https://github.com/hashicorp/terraform/blob/master/states/resource.go#L59)  which causes a nil pointer dereference in [`db.go`](https://github.com/camptocamp/terraboard/blob/master/db/db.go#L93) 
I haven't investigated deeper into Terraform code, just added a simple check. There might be some consequences I am not aware of, but it seems to be working just fine.

Fix nill pointer

---

README.md
config/config.go
config/config_test.go
db/db.go
state/aws.go

I changed `AWS_FILE_EXTENSION` to be `[]string` (or comma-separated list via ENV variable) of extensions, ie `.tfstate,.state`. It's backward compatible and the default value remains the same.

Support multiple file extensions in S3

---

config/config.go
config/config_test.go
config/config_test.yml
state/aws.go

Allows for setting the force path style option. This so that S3 compatible alternatives like Minio can be supported too.
This partly addresses #106.

Allow setting region and force path style for s3

---

README.md

Hello, 
This PR fixes a small issue found at README. According to the config file (https://github.com/camptocamp/terraboard/blob/master/config/config.go#L47), the variable `--app-role-arn` can be provided using the environment variable `APP_ROLE_ARN`.
Regards,

Fix environment variable for APPRoleArn on README

---

db/db.go
go.mod
static/state.html
static/terraboard.js
types/db.go

As discussed in #50, this is a replacement for #51.
I didn't really change much so in terms of the layout it's pretty much the same. I pretty much just rebased, and made a few small changes.
To address a few concerns:
- In terms of layout, there's not a lot to add. The only thing I could think of was adding a blue header bar to the "outputs for module root", but it didn't seem appropriate.
- It's hard to not store values as strings, mostly because we do still need strings. So storing data as something other than strings, will be a lot of work.
- Module outputs do not seem to be available unlike pre-0.12. I think the original code in #51 does deal with it, but I've not tested.
Happy to make any additional changes you like.
Fixes #50, closes #51

Implement Outputs

---

README.md
config/config.go
state/aws.go

Hello, 
The variable `--app-role-arn` provides the feature of assuming an AWS role during runtime. This allows the service to access services from a different account where it is running. Moreover, AWS recommends using this funcionality along with what they call `external id`. This is a random string or number the client must provide to assume an specific role. It acts like a password. 
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html
This PR implements this functionality. I've added a new environment variable called `AWS_EXTERNAL_ID`, a new CLI option `--aws-external-id` and a new YAML parameter: `aws.external-id`. 
If the value is not provided, it will use the default value in a Go string (an empty string `""`), so it should work always. …

Implement AWS EXTERNAL ID feature

---

.github/workflows/golangci-lint.yml
.golangci.yml

Based on the linters used previously with their configurations + the default ones used by golangci
Exhaustive list:
- deadcode
- errcheck
- goimports
- gosec
- gosimple
- govet
- ineffassign
- lll
- misspell
- revive
- staticcheck
- structcheck
- typecheck
- unused
- varcheck

ci: add golangci-lint configuration & workflow

---

.github/workflows/tests.yml

As it stands, the tests are only run on ubuntu-latest and Go 1.15.x.
Should I add some other OS? Or Go versions like 1.16?
Also, with Travis's workflow, you ran the tests twice, once to validate them with "-race" and once to send the coverage to Coveralls. I allowed myself to resemble them as there didn't seem to be any advantages in duplicating them.

ci: add test with Coveralls publish workflow

---

.github/workflows/build.yml

This is the last pipeline PR, with it, all tasks of the make all command (and so executed by TravisCI)  are now handled by Github Actions.
If it's all good I can next remove TravisCI.

ci: add build pipeline

---

.travis.yml

To permanently delete TravisCI, in addition to this PR, there must be a webhook to delete in the repo settings plus, perhaps, branch rules. :rocket: 
Is there still any point in keeping the old lint jobs in the makefile?
We could replace them all with a single job that runs all linters via the golangci-lint config.
It will suffice to install golangci-lint and run the command ```golangci-lint run``` which will use the .golangci.yml config file.
It will also allow to get rid of the .revive.toml file which duplicates the rules that I redefined in golangci.
What do you think about that? :thinking:

ci: remove obsolete travisci pipeline

---

README.md

I also add some HTML style and a collapsed table of content 
The parameters section also include new flags introduced by #165 
Markdown rendered preview available here: https://github.com/hbollon/terraboard/tree/readme-update

docs: update README with missing parameters and new config part layout

---

README.md
config/config.go
example.yml
state/aws.go
test/.gitignore
test/docker-compose.yml

Terraboard is now compatible with MinIO (and normally all others S3 compatble providers) using AWS sdk.
I added **AWS_OTHER_COMPATIBLE_PROVIDER** env variable to disable locks/versions support in order to make the AWS provider compatible with MinIO
The testing purpose environment seems done and ready, it only missing few .tfstates inluded with it.

feat: add test environment with proper docker-compose using MinIO + add compatibility for it to AWS provider

---

docker-compose.yml
test/docker-compose.yml

I fixed docker-compose issue when Terraboard crash if the db isn't fully initialized with a healthcheck depends_on condition.
To do that, I had to upgrade docker-compose format version.

fix: terraboard crash at compose startup if db isn't fully initialized

---

db/db.go
types/db.go

Lineages are now stored in a separate table and are linked to States / Plans via Foreign Keys constraints.
Thanks to the custom migration introduced, current databases should be compatible and automatically update to the new db model.
The migration is carried out automatically when the database is initialized (Init func in db / db.go) and only if the old "lineage" column is still present in the states table.

feat: new standalone lineage table + associated migration

---

api/api.go
db/db.go
main.go
types/db.go
types/json.go

I had a unique endpoint _**/api/plans**_ which is used to submit plan in POST and get ones with GET method:
- GET request: ```<IP>:8080/api/plans?lineage=<LINEAGE>&limit=<Optional limit>``` results will be sorted by most recent to oldest
- POST request: ```<IP>:8080/api/plans``` with as body:
```json
{
"lineage": "<LINEAGE>",
"terraform_version": "0.12.11",
"git_remote": "https://github.com",
"git_commit": "#deadbeef",
"ci_url": "https://github.com/ci",
"source": "foo",
"plan_json": <PLAN_JSON_OUTPUT>
}
```
I also done some tweaks to the plan model: 
- added a missing _omitempty_ tag on **PlanStateResource.SchemaVersion**
- replaced **PlanOutputChange** by generic **Change** structure (and adapted json unmarshalling method), this led to the deletion of the unnecessary …

feat(api): add plan submit/get endpoints  

---

api/api.go
db/db.go
main.go

This PR is very simple as his title shown; it only add a GET endpoint on ```/api/lineages```used to recover all (or a limited amount using ```&limit=```) lineages from the db. They will be sorted by insertion date.
The branch was builded from _api_endpoints_ one on my fork so #175 is needed for this PR to be ready :smiley:

feat(api): add endpoint to get lineages from database

---

db/db.go
types/db.go

The lineage migration will now try to recover one lineage from other states with same path or set it to null if it fail when a state don't have one.
Also fix an issue where some lineages were ignored on migration

feat(migration): add migration compatibility with states without lineage

---

.gitignore
static/terraboard-vuejs/src/components/Charts.vue
static/terraboard-vuejs/src/components/Footer.vue
static/terraboard-vuejs/src/components/Navbar.vue
static/terraboard-vuejs/src/components/StatesList.vue
static/terraboard-vuejs/src/views/Search.vue
static/terraboard-vuejs/src/views/State.vue

- Ignore dist
- fix(frontend): remove localhost from URLs

fix: remove localhost from URLs

---

static/terraboard-vuejs/src/components/StatesList.vue
static/terraboard-vuejs/src/views/Search.vue

Signed-off-by: Raphaël Pinson <raphael.pinson@camptocamp.com>

feat(frontend): set role=button on list carets

---

static/terraboard-vuejs/src/views/State.vue

I also fixed ressource count badge displayed next to module name

fix(frontend): resource filter on state view now works

---

static/terraboard-vuejs/src/views/State.vue

+ feat(frontend): resource filter now match any substring in res path or name
I also optimized module span updating (the badge which indicate how many resources a module have and the number of them which match with the filter) by moving the code which handle it to the `updated` hook.

fix(frontend): performance issue with resource filter with multiples modules

---

static/terraboard-vuejs/src/components/PlanContent.vue
static/terraboard-vuejs/src/views/Plan.vue
static/terraboard-vuejs/src/views/State.vue

* feat(frontend): add link to go back to lineage on plan/state views

fix(frontend): undefined error on plan view without outputs changes

---

api/api.go
db/db.go
main.go
static/terraboard-vuejs/src/views/Lineage.vue
static/terraboard-vuejs/src/views/Plan.vue
static/terraboard-vuejs/src/views/PlansExplorer.vue

feat(frontend): add loading spinner during plan fetching
This PR fix performances issues observed during plans fetching due to huge size of the response.
To achieve that I have: 
* Added an endpoint `/api/plans/summary` which returns the metadata (data added by the wrapper) of the plans and I modified the view to use it on: the lineage view, the "plans explorer" view and the view of a plan (the last 10 plans displayed on the left)
* Added the possibility to pass `?planid=X` as a parameter to `/api/plans` in GET which allows it to return only a plan from its ID (since now I have to make an additional request to display a plan)
* Added a loading indicator (a spinner with Font Awesome) plan fetching since plans can be a few MO individually.

fix(frontend): performances issue on plans fetching

---

state/aws.go
state/aws_test.go

Upgrade to the newest AWS API For ListObjectsV2 and then also add the ability to have more than 1000 state files

feat: allow more than 1000 state files

---

README.md

Fixing typo - WS_DYNAMODB_TABLE should be AWS_DYNAMODB_TABLE

Fix typo - WS_DYNAMODB_TABLE to AWS_DYNAMODB_TABLE

---

README.md
config/config.go
config/config_test.go
config/config_test.yml
test/multiple-minio-buckets/config.yml
test/multiple-minio-buckets/docker-compose.yml

**Goal**:
Allow resolving environment variables in the yaml config file
**Done**:
Call `os.ExpandEnv` before unmarshal the yaml file

Add ability to resolve environment variables in yaml config

---

README.md

This PR adds complementary documentation on how to setup auth headers passed by proxies.
Signed-off-by: Renato Farias <renatocdfs@gmail.com>

proxy auth headers complementary documentation
